---
- name: Show off some basic Ansible features
  hosts: local
  become: true
  remote_user: vagrant
  # user: root
  # remote_user: user
  # sudo: yes
  vars:
    url: letsdevelop.info
    document_root: /var/www

  roles:
    - common
    - nginx
    - php
    - nodejs
