---
- name: GET NodeJS
  get_url:
    url=https://deb.nodesource.com/setup_6.x
    dest={{ home }}/nodesource_setup.sh
    mode=775

- name: Install NodeJS script
  command: bash {{ home }}/nodesource_setup.sh

- name: Install NodeJS
  apt: name={{item}} state=present update_cache=true
  with_items:
    - nodejs
    - build-essential
