---
# ==============================================================================
# Getting home-page project or index.html
- name: Setting up homepage project
  git:
    repo=https://github.com/martinsimonovski/letdevelop.git
    dest={{ projectsHome }}
    accept_hostkey=yes
    key_file=/Users/martin/.ssh/id_martin
  notify:
    - reload nginx
# ==============================================================================
# Getting Globe project and initializing it
- name: Setting up globe project
  git:
    repo=https://github.com/martinsimonovski/globe.git
    dest={{ projectsGlobe }}
    accept_hostkey=yes
    key_file=/Users/martin/.ssh/id_martin
    version=relay-server
  register: git_finished

- name: NPM cache clean
  command: npm cache clean

# this has problems with sqlite3
# - name: Running NPM install
#   npm:
#     path={{ projectsGlobe }}
#     state=present
#   register: npm_finished
  # when: git_finished.changed

- name: Installing Globe (package.json) with yarn
  command: yarn
    chdir={{ projectsGlobe }}
  register: npm_finished
  when: git_finished.changed

# If they are started already so we don't get error
- name: Deleting pm2 processes
  command: pm2 kill

- name: Starting the server with pm2
  command: pm2 start --interpreter babel-node {{ projectsGlobe }}/server.js --name "globe"
  when: npm_finished.changed
  notify:
    - reload nginx
# ==============================================================================
# Installing Risk-hedge project
