---
  - name: Update apt cache
    apt: update_cache=yes
# ==============================================================================

  - name: Installing Zsh and git
    apt: pkg=zsh,git state=latest
    register: installation

  - name: Cloning oh-my-zsh
    git:
      repo=https://github.com/robbyrussell/oh-my-zsh
      dest=~/.oh-my-zsh
    when: installation|success
    register: cloning

  - name: Creating new ~/.zshrc
    copy:
      src=~/.oh-my-zsh/templates/zshrc.zsh-template
      dest=~/.zshrc
    when: cloning|success
# ==============================================================================

  - name: Create Projects root folder
    file: path={{ projectsRoot }} state=directory owner=www-data group=www-data mode=0755 recurse=yes

  - name: Create alias for projects folder
    command: alias projects='cd {{ projectsRoot }}/$1'

  - name: Create Projects folders
    file: path={{ item }} state=directory owner=www-data group=www-data mode=0755 recurse=yes
    with_items:
      - "{{ projectsHome }}"
      - "{{ projectsGlobe }}"
      - "{{ projectsRisk }}"
# ==============================================================================
