---
# ==============================================================================
# Add repository
- name: Add repository for PHP 7.0
  apt_repository:
    repo="ppa:ondrej/php"
    update_cache=yes

# ==============================================================================
# PHP 7.0
- name: Install PHP 7.0, PHP-SQLITE(3) 7.0
  apt: name={{item}} state=present update_cache=true
  with_items:
    - php7.0-common
    - php7.0-cli
    - php7.0-intl
    - php7.0-curl
    - php7.0-cgi
    - php7.0-fpm
    - php7.0-json
    - php7.0-gd
    - php7.0-sqlite3
  notify:
    - restart php
    - restart nginx
# ==============================================================================
# Edit php.ini
- name: Ensure php5-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php
    - restart nginx
# ==============================================================================
